### ISSUE TITLE
Make cancel print dialog box smaller

### ISSUE THREAD

**Issue by purist69** [BillyBlaze/OctoPrint-TouchUI#334] opened 2019-10-15 00:11 UTC
I run TouchUI on a 800x480 touchscreen.  When I press stop on a print job a confirmation dialog comes up that is too large and the button appears off the screen.  Please resolve.

**Comment by BillyBlaze** [comment] 2019-10-18 18:25
Thanks for reporting, I'll have a look at this for the next release.

**Comment by ellindsey** [comment] 2019-10-28 01:48
I may be having this issue as well.  When confirmation dialogs come up, the UI will frequently ignore me pressing "yes" and act as if I pressed "no".

**Comment by compmas2** [comment] 2020-01-10 02:11
I have been seeing the same issue. This is not just the print job cancel confirmation screen, but any confirmation screen within TouchUI when using a 800x480 touchscreen.

Additionally on the 800x480 touchscreen, the three horizontal lines which is supposed to bring up more plugins or menus is sometimes hijacked by the tab icon behind it and that is pressed instead of the three horizontal lines icon.

**Comment by BillyBlaze** [comment] 2020-03-07 19:15
Closing this issue as its duplicate of #296 
For updates follow that issue thread

**Closed as completed by BillyBlaze** 2020-03-07 19:15 UTC
Labels: bug, pending
