### ISSUE TITLE
Can't load touch ui after octoprint 1.3.9 update

### ISSUE THREAD

**Issue by YaYaLanD** [BillyBlaze/OctoPrint-TouchUI#228] opened 2018-07-28 07:52 UTC
Hello !

Since the latest update, i can't access the touch ui on my 3.5" screen, i get a failed to load in red.
Git pull tells me i have the latest version of touch ui.

I hop you will be able to solve this soon : )

Thank you for all your efforts !
Regards

**Comment by IdefixRC** [comment] 2018-07-28 08:41
same issue here. This was already mentioned in an earlier bug report though.
Linking it here #223

**Comment by YaYaLanD** [comment] 2018-07-28 08:54
yeah i saw the bug report #223 but as this # is related with RC2 of 1.3.9, i thought i might open another thread.

**Comment by lexter12** [comment] 2018-07-28 12:23
Same here. "Startup Failed... " with nothing in the octoprint log file

**Comment by ram64** [comment] 2018-07-28 20:13
Same. TouchUI works well on desktop, in Chrome browser but on my RPI B3+ with official touchscreen I get **Connecting to TouchUI failed...**

**Comment by scotthay513** [comment] 2018-07-28 21:33
Same here, was working well before the last update and now the error message upon loading TouchUI.  Octoprint is working fine however, I can still access it through the webserver.

**Comment by Kremptor** [comment] 2018-07-28 22:01
Same Problem, TouchUI does not start after update 1.3.9.

**Comment by Kremptor** [comment] 2018-07-28 22:51
I did a downgrade to 1.3.8 and TouchUI is working.

~/oprint/bin/pip install https://github.com/foosel/OctoPrint/archive/1.3.8.zip
sudo reboot

**Comment by IdefixRC** [comment] 2018-07-29 01:54
thanks. going back to 1.3.8 till this is fixed

**Comment by ghost** [comment] 2018-07-29 04:02
Same here.

**Comment by jamskate** [comment] 2018-07-29 14:28
Having same issue as well..

**Comment by bolsoncerrado** [comment] 2018-07-30 17:33
Same here on Pi3B and Pi3B+

**Comment by Kmarkopl** [comment] 2018-07-30 23:30
Have same issue, PI3+ TFT 5" screen

**Comment by Nappyy** [comment] 2018-08-02 17:08
same here, pi3b+

**Comment by Tronnic** [comment] 2018-08-04 00:09
Same here, Pi3B

**Comment by TisDone** [comment] 2018-08-04 20:39
Another report, same problem. Pi 3b+ with the official Raspberry 7" Touchscreen.

**Comment by thedragonlord71** [comment] 2018-08-05 08:59
Another report, me too with the official Raspberry 7" Touchscreen

**Comment by einfachTobi** [comment] 2018-08-13 12:43
Have the same issue and got a workaround for this:
Edit ~/TouchUI-autostart/chromium.xinit:
`nano ~/TouchUI-autostart/chromium.xinit `

Change the variable CHROME_ARGS to:
`CHROME_ARGS="   --no-first-run --kiosk $TOUCHUI_ARGS $TOUCHUI_DEBUG
                --dns-prefetch-disable --disable-sync-preferences --disk-cache-size=1048576
                --disable-java --disable-plugins --disable-extensions --disable-infobars
                --user-agent='TouchUI (X11, Chrome $CHROME_VERSION) (P:$PORT)'
                --start-maximized --window-position=0,0
		'http://localhost'"
`
(last line changed)
This will not load the startup-screen of TouchUI-autostart, but at least TouchUI will start.
Verify with a restart of the service or reboot of the pi
`sudo service touchui restart` or `sudo reboot`

For me it worked. Can anyone confirm?

**Comment by bolsoncerrado** [comment] 2018-08-13 18:20
Wow thanks for that ;)

**Comment by bolsoncerrado** [comment] 2018-08-13 18:39
I can confirm @einfachTobi 's solution works....

BUT NOW

I have an issue while trying to LOGIN using TouchUI. It won't do anything. I can touch any options on the menu, and move thru all the screens TouchUI offers for Octoprint, but it just refuses to show login fields :( ie nothing happens when I click Login except the menu disappearing, of course.

**Comment by jraydoran** [comment] 2018-08-13 18:52
@einfachTobi
Same issue as @bolsoncerrado. Cannot "login" and no "control" screen.

Kind Regards
Jason

**Comment by bolsoncerrado** [comment] 2018-08-13 18:52
@jraydoran  the "no control screen" is normal because you're not logged in.

**Comment by jraydoran** [comment] 2018-08-14 04:31
Makes sense. Thank you!!

**Comment by einfachTobi** [comment] 2018-08-14 06:59
I'm sorry i can't help with that because I don't use the login and dont't know how it works. Maybe you can find another method for authentification and deactivate the octoprint login until the underlying problem with TouchUI-autostart has been solved.

**Comment by jonnyhifi** [comment] 2018-08-23 10:35
yes ! worked for me, I never thought it would take 2 man days to configure a raspberry pi from scratch... but I guess kids can do it... ;)

**Comment by jace055** [comment] 2018-08-26 02:28
After using einfachTobi's technique above, reboot then deactivate the touchui plugin.  Reboot once again to the normal octoprint screen.  login and check the remember me box.  Reactive the touchui plugin and reboot one last time and you should be logged in and in the touch ui.

**Comment by nosbor78** [comment] 2018-08-29 03:40
@Kremptor thank you, that worked.

I'm suffering from the same problem.
RPI 3 B+, RPI official touchscreen, 5V 3A PS, no lightening bolt, latest Octopi image.

**Comment by BillyBlaze** [comment] 2018-09-01 17:50
Thanks everyone for the feedback, I am currently working on this issue and plan to release a.s.a.p.

However this issue is a similar to #221 so therefor I am closing this.

**Closed as completed by BillyBlaze** 2018-09-01 17:50 UTC
Labels: pending
