### ISSUE TITLE
iOS Safari Login Box Issue

### ISSUE THREAD

**Issue by Sunoo** [BillyBlaze/OctoPrint-TouchUI#163] opened 2017-10-25 16:28 UTC
On Safari on iOS, when you tap the Login option, the menu expands but the login UI elements do not appear. Scrolling the screen usually seems to resolve the issue.

**Comment by veggie2u** [comment] 2017-10-27 20:53
This is not just Safari iOS, but I have duplicated the issue there as well.  I have a pi running epiphany fullscreen with an Adafruit touch screen. I think everything else is OK, but login has issues with that configuration also. If I scroll first, then press the login item I can then see the name/password fields. Part of the issue is the limited size of the screen on the PiTFT. 

The other issue on the PiTFT is that I can't press login. The UI scrolls up and I can't see below the remember me, which I can seem to check either. I then scroll the page, press login, and the UI scrolls, never submitting the login.

I was able to work around this issue by turning INACTIVE the onscreen keyboard and using a regular usb keyboard, tabbing to the login button and pressing return.

**Comment by BillyBlaze** [comment] 2017-12-12 17:04
Thanks both for reporting!

@Sunoo, the issue has been found and the fix is currently pushed to maintenance and will be released very soon.

@veggie2u, Epiphany support have been dropped for a while now (mostly because of the bad performance and lack of some important standards). I suggest upgrading to Chromium and installing the TouchUI bootloader as instructed on my wiki.

**Closed as completed** 2017-12-12 18:19 UTC
Labels: fixed
