### ISSUE TITLE
TouchUI not displaying on touch screen but displays on webui

### ISSUE THREAD

**Issue by ianjolin** [BillyBlaze/OctoPrint-TouchUI#199] opened 2018-03-21 02:58 UTC
I had some issues early on and could not get my RPi touchscreen UI to display. I installed the TOuchUI prior to getting my touchscreen UI operational. I attempted an uninstall reinstall with the same results.
I assume this is a minor fix but I am unsure where to start, any help would be appreciated.

**Comment by BillyBlaze** [comment] 2018-03-21 22:28
Duplicate of #200 ?

**Closed as completed by BillyBlaze** 2018-03-21 22:28 UTC
