### ISSUE TITLE
TouchUI stops working when Shutdown Printer Plugin is active

### ISSUE THREAD

**Issue by ARCH-3D** [BillyBlaze/OctoPrint-TouchUI#302] opened 2019-05-27 16:49 UTC
Hello,

After installing the last upgrade the TouchUI stops workinkg. And the problem is with Shutdown Printer plugin. When the ShutDown Printer plugin is active the TouchUI stops working and when is disabled the TouchUI works properly. I would like to know if you could solve this incompatibility. Many thanks.

Best regards,

**Comment by BillyBlaze** [comment] 2019-05-27 17:03
Hello,

Thanks for reporting. I can reproduce your issue and will fix this in the upcoming release.

**Comment by BillyBlaze** [comment] 2019-05-27 17:15
This has been fixed on the maintenance branch and will be released in the next version. There is no E.T.A. but if you want this you could install TouchUI from maintenance.

Install with this link: https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/maintenance.zip

**Comment by ARCH-3D** [comment] 2019-05-27 18:16
sorry for the question. But how can I install with this link: https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/maintenance.zip ?

**Comment by ARCH-3D** [comment] 2019-05-27 18:17
And many thanks for your help :)

**Comment by ARCH-3D** [comment] 2019-05-27 19:12
Many thanks BillyBlaze :) It works now! Great Work ! 👍

**Comment by Kuenstler79** [comment] 2019-08-19 07:32
How can I install a zip file from the maintenance branch? Unfortunately I have only little linux experience.

**Comment by Varming73** [comment] 2020-01-25 15:26
Im on TouchUI: 0.3.13, OctoPrint: 1.3.12  and Shutdown Printer (1.0.8) and the problem is still there. What am I missing?

**Closed as completed** 2020-03-11 18:30 UTC
Labels: bug, fixed, confirmed
