### ISSUE TITLE
hang at "Loading TouchUI"

### ISSUE THREAD

**Issue by Ch3fk0ch88** [BillyBlaze/OctoPrint-TouchUI#234] opened 2018-08-19 15:59 UTC
Hello,
i installed everything according to the instructions on github.
Unfortunately the display hangs at "Loading TouchUI" and I don't know why.

Can anyone help me?

If you need any information, please tell me which and how I can get it.

Thanks.

**Comment by bearink** [comment] 2018-08-20 23:44
I am having the same issue, reinstalled fresh and tried multiple fixes around here.

first it connects then jump on to Loading TouchUI for a while before a fail
then after touching the screen, it returns to loading TouchUI

**Comment by smiler** [comment] 2018-08-23 20:34
I have the same issue. New install following https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light)

**Comment by smiler** [comment] 2018-08-23 20:43
Most likely a duplicate of #228

**Comment by redwolf3773** [comment] 2018-08-29 16:28
I am having the same issue as well. It hangs up at Loading Touch UI. This is not a new install. I did update Octopi to the latest version and it seemed to happen then.

**Comment by bearink** [comment] 2018-08-29 18:52
I did reinstall the whole thing again without updating octopi this time and everything works as it should.

**Comment by BillyBlaze** [comment] 2018-09-01 17:43
Thanks everyone for the feedback, I am currently working on this issue and plan to release a.s.a.p.

However this issue is a similar to #221 so therefor I am closing this.

**Closed as completed by BillyBlaze** 2018-09-01 17:43 UTC
