### ISSUE TITLE
No camera feed on TouchUi

### ISSUE THREAD

**Issue by Kev7274** [BillyBlaze/OctoPrint-TouchUI#125] opened 2017-05-11 14:41 UTC
Everything is working fine,except I can't get any camera feed when I run TouchUi. All desktop functions are ok.

I'm using the Official Pi touchscreen 7".

**Comment by BillyBlaze** [comment] 2017-05-13 11:06
Duplicate of #123

Please see that issue for more information

**Closed as completed by BillyBlaze** 2017-05-13 11:06 UTC
